### PR TITLE
Added styles to the NavBar

### LINKED ISSUE #4: Add styles to the NavBar
I'd like to add styles to the website's NavBar to match the design and enhance its visual appeal and functionality.

### PR DESCRIPTION
**Pull request by Jony-Jas**
Successfully added styles to the NavBar based on the design given
fixes #4 

Preview >>
 
desktop
mobile

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
The overall design looks good,will merge it soon,thank you

**Comment by karthiknadar1204** [comment]
@Jony-Jas Please resolve the conflicts, will merge it as soon as it is done

**Review by Akshatchaube01 — APPROVED** [review]

**Comment by durgaprasad118** [comment]
@karthiknadar1204  review and approve this I have added the custom names to colors to the rest of the componets. If this is done i will add to this also and will create a PR. Thankyou.

**Comment by tejanamala15** [comment]
Yes please, so that I can add the in page navigation. Thank you.

**Comment by karthiknadar1204** [comment]
@Jony-Jas any update

**Comment by Jony-Jas** [comment]
All the conflicts were resolved and seem good to merge

**Comment by durgaprasad118** [comment]
@karthiknadar1204 review this and merge it.

**Pull request merged**
